apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ztd3gukly-dotnet-basic
  janus-idp.io/tekton: ztd3gukly-dotnet-basic
  backstage.io/kubernetes-id: ztd3gukly-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ztd3gukly-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
